Merged PR 53675: Fix WP CLI autoload issue in composer-based WordPress
## What's being changed

We've moved the autoloader reference _above_ all use statements in `Dotdigital_WooCommerce_Bootstrapper`.

## Why it's being changed

While this change feels sensible regardless, it only surfaced in a WordPress where composer is used to install plugins and other dependencies. And even then, it only showed up when running `wp` on the command line. In this case, we saw this error:
```
Fatal error: Uncaught Error: Class 'Dotdigital_WooCommerce\Includes\Dotdigital_WooCommerce' not found in /Sites/wordpress-composer/wp-content/plugins/dotdigital-for-woocommerce/class-dotdigital-woocommerce-bootstrapper.php:131
```

## How to review / test this change

- Take a regular WordPress and run `composer init` in the root folder
- Your composer file should contain:
```
    "require": {
        "wpackagist-plugin/woocommerce":"^7.8",
        "wpackagist-plugin/dotdigital-for-woocommerce":"^1.4"
    },
    "repositories":[
        {
            "type":"composer",
            "url":"https://wpackagist.org"
        }
    ],
```
- Try running `wp plugin activate dotdigital-for-woocommerce`, you should see a Fatal Error in the terminal
- Now go over to your other WordPress where you have your version-controlled Woo plugin files
- Run `composer prefix-dependencies` over there
- Now move the build_prefixed files over to replace the wpackagist plugin files
- Re-run the wp command in your composer WordPress
- The plugin should be activated

Related work items: #252280